# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../matrix_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from loading import loading
from pygame import mixer

class Ui_MainWindow(object):
    def __init__(self):
        mixer.init()
        mixer.music.load("/music/Aastra.mp3")
        mixer.music.set_volume(0.7)
        mixer.music.play()

    def loading(self , application):
        self.window = QtWidgets.QMainWindow()
        self.ui = loading(application)
      
        self.ui.setupUi(self.window)
        self.window.show()















    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\\images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 451, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/TONY STARK/Pictures/Matrix_logo2.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 170, 221, 71))
        self.label_2.setStyleSheet("color:red;\n"
"font: 22pt \"Gabriola\";\n"
"font:bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.label_3.setStyleSheet("background-color:black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/TONY STARK/Desktop/bg-matrix.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 220, 291, 261))
        self.label_4.setStyleSheet("color:rgb(8, 8, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\PROJECT JARVIS\images\Pngtreebluetechnologybutton5402545"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 430, 291, 261))
        self.label_5.setStyleSheet("color:rgb(8, 8, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\PROJECT JARVIS\images\Pngtreebluetechnologybutton5402545"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 430, 291, 261))
        self.label_6.setStyleSheet("color:rgb(8, 8, 255);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\PROJECT JARVIS\images\Pngtreebluetechnologybutton5402545"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(630, 220, 291, 261))
        self.label_7.setStyleSheet("color:rgb(8, 8, 255);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\PROJECT JARVIS\images\Pngtreebluetechnologybutton5402545"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.add = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.loading("add"))
        self.add.setGeometry(QtCore.QRect(170, 322, 171, 51))
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.add.setStyleSheet("border: 0px solid;\n"
"\n"
"color:rgb(14, 159, 255);\n"
"font: 81 16pt \"Rockwell Extra Bold\";")
        self.add.setObjectName("add")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(670, 320, 211, 51))
        self.subtract.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.subtract.setStyleSheet("border: 0px solid;\n"
"\n"
"color:rgb(14, 159, 255);\n"
"font: 81 16pt \"Rockwell Extra Bold\";")
        self.subtract.setObjectName("subtract")
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setGeometry(QtCore.QRect(700, 530, 171, 51))
        self.div.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.div.setStyleSheet("border: 0px solid;\n"
"\n"
"color:rgb(14, 159, 255);\n"
"font: 81 16pt \"Rockwell Extra Bold\";")
        self.div.setObjectName("div")
        self.mul = QtWidgets.QPushButton(self.centralwidget)
        self.mul.setGeometry(QtCore.QRect(130, 530, 251, 51))
        self.mul.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.mul.setStyleSheet("border: 0px solid;\n"
"\n"
"color:rgb(14, 159, 255);\n"
"font: 81 16pt \"Rockwell Extra Bold\";")
        self.mul.setObjectName("mul")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.add.raise_()
        self.subtract.raise_()
        self.div.raise_()
        self.mul.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MATRIX SOLVER"))
        self.label_2.setText(_translate("MainWindow", "By -  ANANT PAREEK"))
        self.add.setText(_translate("MainWindow", "ADDITION"))
        self.subtract.setText(_translate("MainWindow", "SUBTRACTION"))
        self.div.setText(_translate("MainWindow", "DIVISION"))
        self.mul.setText(_translate("MainWindow", "MULTIPLICATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
