# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import time
class loading(object):
    def __init__(self , window_to_open):
         pass
    def progress(self):
        while True :
                time.sleep(1)
                if self.current_value  <100:
                    self.current_value += 10
                    self.progressBar.setValue(self.current_value)
                else:
                    quit()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.label_3.setStyleSheet("background-color:black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/TONY STARK/Desktop/bg-matrix.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.current_value = 0
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(350, 330, 361, 111))
        self.progressBar.setProperty("value", self.current_value)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 450, 251, 61))
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"\n"
"font: 26pt \"Ravie\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget , clicked=lambda:self.progress())
        self.pushButton.setGeometry(QtCore.QRect(440, 620, 131, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setStyleSheet("border: 2px solid red;\n"
"border-radius : 35px;\n"
"font: 16pt \"New Walt Disney UI\";\n"
"color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 170, 127);\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT"))
        self.label.setText(_translate("MainWindow", "LOADING ......"))
        self.pushButton.setText(_translate("MainWindow", "LETS GO "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = loading()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
