# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mul3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.label_3.setStyleSheet("background-color:black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/TONY STARK/Desktop/bg-matrix.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, -30, 701, 191))
        self.label.setStyleSheet("font: 42pt \"New Walt Disney UI\";\n"
"text-decoration: underline;\n"
"\n"
"color: rgb(0, 157, 255);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 140, 441, 481))
        self.widget.setStyleSheet("border: 5px solid red;")
        self.widget.setObjectName("widget")
        self.fff = QtWidgets.QSpinBox(self.widget)
        self.fff.setGeometry(QtCore.QRect(10, 10, 81, 61))
        self.fff.setObjectName("fff")
        self.fff_2 = QtWidgets.QSpinBox(self.widget)
        self.fff_2.setGeometry(QtCore.QRect(170, 10, 81, 61))
        self.fff_2.setObjectName("fff_2")
        self.fff_3 = QtWidgets.QSpinBox(self.widget)
        self.fff_3.setGeometry(QtCore.QRect(340, 10, 81, 61))
        self.fff_3.setObjectName("fff_3")
        self.fff_4 = QtWidgets.QSpinBox(self.widget)
        self.fff_4.setGeometry(QtCore.QRect(10, 170, 81, 61))
        self.fff_4.setObjectName("fff_4")
        self.fff_5 = QtWidgets.QSpinBox(self.widget)
        self.fff_5.setGeometry(QtCore.QRect(170, 170, 81, 61))
        self.fff_5.setObjectName("fff_5")
        self.fff_6 = QtWidgets.QSpinBox(self.widget)
        self.fff_6.setGeometry(QtCore.QRect(340, 160, 81, 61))
        self.fff_6.setObjectName("fff_6")
        self.fff_7 = QtWidgets.QSpinBox(self.widget)
        self.fff_7.setGeometry(QtCore.QRect(10, 380, 81, 61))
        self.fff_7.setObjectName("fff_7")
        self.fff_8 = QtWidgets.QSpinBox(self.widget)
        self.fff_8.setGeometry(QtCore.QRect(170, 380, 81, 61))
        self.fff_8.setObjectName("fff_8")
        self.fff_9 = QtWidgets.QSpinBox(self.widget)
        self.fff_9.setGeometry(QtCore.QRect(340, 380, 81, 61))
        self.fff_9.setObjectName("fff_9")
        self.compute = QtWidgets.QPushButton(self.centralwidget)
        self.compute.setGeometry(QtCore.QRect(460, 630, 101, 61))
        self.compute.setStyleSheet("color:rgb(255, 85, 0);\n"
"font: 12pt \"Ravie\";\n"
"background-color:white\n"
"\n"
"")
        self.compute.setObjectName("compute")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(550, 140, 441, 481))
        self.widget_2.setStyleSheet("border: 5px solid blue;")
        self.widget_2.setObjectName("widget_2")
        self.fff_10 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_10.setGeometry(QtCore.QRect(10, 10, 81, 61))
        self.fff_10.setObjectName("fff_10")
        self.fff_11 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_11.setGeometry(QtCore.QRect(170, 10, 81, 61))
        self.fff_11.setObjectName("fff_11")
        self.fff_12 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_12.setGeometry(QtCore.QRect(340, 10, 81, 61))
        self.fff_12.setObjectName("fff_12")
        self.fff_13 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_13.setGeometry(QtCore.QRect(10, 170, 81, 61))
        self.fff_13.setObjectName("fff_13")
        self.fff_14 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_14.setGeometry(QtCore.QRect(170, 170, 81, 61))
        self.fff_14.setObjectName("fff_14")
        self.fff_15 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_15.setGeometry(QtCore.QRect(340, 160, 81, 61))
        self.fff_15.setObjectName("fff_15")
        self.fff_16 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_16.setGeometry(QtCore.QRect(10, 380, 81, 61))
        self.fff_16.setObjectName("fff_16")
        self.fff_17 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_17.setGeometry(QtCore.QRect(170, 380, 81, 61))
        self.fff_17.setObjectName("fff_17")
        self.fff_18 = QtWidgets.QSpinBox(self.widget_2)
        self.fff_18.setGeometry(QtCore.QRect(340, 380, 81, 61))
        self.fff_18.setObjectName("fff_18")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT"))
        self.label.setText(_translate("MainWindow", "MULTIPLICATION OF MATRIX"))
        self.compute.setText(_translate("MainWindow", "COMPUTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
