# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mul2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/library-logo-design-template-45579f2f9eaf725821b915b523f191eb_screen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1001, 771))
        self.label_3.setStyleSheet("background-color:black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/TONY STARK/Desktop/bg-matrix.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, -30, 661, 191))
        self.label.setStyleSheet("font: 42pt \"New Walt Disney UI\";\n"
"text-decoration: underline;\n"
"\n"
"color: rgb(0, 157, 255);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 140, 441, 481))
        self.widget.setStyleSheet("border: 5px solid red;")
        self.widget.setObjectName("widget")
        self.fff = QtWidgets.QSpinBox(self.widget)
        self.fff.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.fff.setObjectName("fff")
        self.ffs = QtWidgets.QSpinBox(self.widget)
        self.ffs.setGeometry(QtCore.QRect(320, 10, 111, 81))
        self.ffs.setObjectName("ffs")
        self.fsf = QtWidgets.QSpinBox(self.widget)
        self.fsf.setGeometry(QtCore.QRect(10, 360, 111, 81))
        self.fsf.setObjectName("fsf")
        self.fss = QtWidgets.QSpinBox(self.widget)
        self.fss.setGeometry(QtCore.QRect(310, 360, 111, 81))
        self.fss.setObjectName("fss")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(540, 140, 441, 481))
        self.widget_2.setStyleSheet("border:5px solid blue;")
        self.widget_2.setObjectName("widget_2")
        self.sff = QtWidgets.QSpinBox(self.widget_2)
        self.sff.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.sff.setObjectName("sff")
        self.sfs = QtWidgets.QSpinBox(self.widget_2)
        self.sfs.setGeometry(QtCore.QRect(320, 10, 111, 81))
        self.sfs.setObjectName("sfs")
        self.ssf = QtWidgets.QSpinBox(self.widget_2)
        self.ssf.setGeometry(QtCore.QRect(10, 360, 111, 81))
        self.ssf.setObjectName("ssf")
        self.sss = QtWidgets.QSpinBox(self.widget_2)
        self.sss.setGeometry(QtCore.QRect(310, 360, 111, 81))
        self.sss.setObjectName("sss")
        self.compute = QtWidgets.QPushButton(self.centralwidget)
        self.compute.setGeometry(QtCore.QRect(460, 630, 101, 61))
        self.compute.setStyleSheet("color:rgb(255, 85, 0);\n"
"font: 12pt \"Ravie\";\n"
"background-color:white\n"
"\n"
"")
        self.compute.setObjectName("compute")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBRARY MANAGEMENT"))
        self.label.setText(_translate("MainWindow", "MULTIPLICATION OF MATRIX"))
        self.compute.setText(_translate("MainWindow", "COMPUTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
